services:
  backend:
    image: library:prod
    build:
      context: ./biblioteka_drf
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./biblioteka_drf:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy

  frontend_vue:
    image: library:vue
    build:
      context: ./biblioteka_drf_vue
    ports:
      - "8001:5173"
    volumes:
      - ./biblioteka_drf_vue:/app
    depends_on:
      backend:
        condition: service_started

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
